- operation: Add
  participant_description:
    name: pinky_01
    group: project1_pinky
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.050000000000000003
        - 0.10000000000000001